# Generated by Django 3.1.6 on 2021-02-28 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='ProductComment',
        ),
    ]
