# Generated by Django 3.1.6 on 2021-03-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210303_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='text_1',
            field=models.TextField(max_length=500, null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='text_2',
            field=models.TextField(max_length=200, verbose_name='Плюсы'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='text_3',
            field=models.TextField(max_length=200, verbose_name='Минусы'),
        ),
    ]
