# Generated by Django 3.1.6 on 2021-03-03 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_auto_20210303_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='text_1',
            field=models.TextField(max_length=500, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='text_2',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Плюсы'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='text_3',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Минусы'),
        ),
    ]
