# Generated by Django 3.1.6 on 2021-03-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210303_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='mark',
            field=models.CharField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=7),
        ),
    ]
