# Generated by Django 3.1.6 on 2021-03-03 21:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='mark',
            field=models.CharField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], default=Decimal('0.00'), max_length=7),
        ),
    ]
