# Generated by Django 3.1.6 on 2021-03-04 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210304_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='dislike',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='like',
            new_name='likes',
        ),
    ]
