# Generated by Django 3.1.6 on 2021-03-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210304_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='mark',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=4),
        ),
    ]
