# Generated by Django 3.1.6 on 2021-03-03 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_post_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_like_or_dislike', models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike'), (None, 'None')], default=None, max_length=7)),
            ],
        ),
        migrations.RenameModel(
            old_name='Like',
            new_name='PostLike',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='counter',
            new_name='comment_dislikes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='dislikes',
            new_name='post_dislikes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='post_likes',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='like_or_dislike',
            new_name='post_like_or_dislike',
        ),
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='for_com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comment'),
        ),
        migrations.AddField(
            model_name='commentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
