# Generated by Django 3.1.6 on 2021-03-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210303_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlike',
            old_name='comment_like_or_dislike',
            new_name='like_or_dislike',
        ),
        migrations.RenameField(
            model_name='postlike',
            old_name='post_like_or_dislike',
            new_name='like_or_dislike',
        ),
    ]
