# Generated by Django 3.1.6 on 2021-03-16 09:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productreview_productreviewlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=3, null=True),
        ),
    ]
