# Generated by Django 3.1.6 on 2021-03-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_rating'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together={('slug',)},
        ),
    ]
